assets:
  css:
    - bundles/os2displayscreen/assets/build/os2displayscreen.min.css
  js_prod:
    - bundles/os2displayscreen/assets/build/os2displayscreen.min.js

apps:
  screenApp:
    container: false
    files:
      - bundles/os2displayscreen/apps/screenApp/screenApp.js
    dependencies:
      - busModule
      - mainModule
      - pascalprecht.translate
