os2display_screen_push:
    path:     /screen
    defaults: { _controller: Os2DisplayScreenBundle:Default:push }

os2display_screen_pull:
    path:     /screen/display/{screenId}
    defaults: { _controller: Os2DisplayScreenBundle:Default:pull }

os2display_get_serialized_screen:
    path:     /screen/serialized/{screenId}
    defaults: { _controller: Os2DisplayScreenBundle:Default:getCurrentScreenContent }
